skip_vim_plugin "taglist"
skip_vim_plugin "snipmate"

vim_plugin_task "tlib",               "git://github.com/tomtom/tlib_vim.git"
vim_plugin_task "vim-addon-utils",    "git://github.com/MarcWeber/vim-addon-mw-utils.git"
vim_plugin_task "snipmate-garbas",    "git://github.com/garbas/vim-snipmate.git"
vim_plugin_task "snipmate-snippets",  "git://github.com/honza/snipmate-snippets.git"
vim_plugin_task "bufexplorer",        "git://github.com/vim-scripts/bufexplorer.zip.git"
vim_plugin_task "tagbar",             "git://github.com/majutsushi/tagbar.git"
vim_plugin_task "pep8",               "git://github.com/nvie/vim-pep8.git"
vim_plugin_task "PIV",                "git://github.com/spf13/PIV.git"
